sudo: false
language: rust
rust: 
  - nightly
  - stable
  - beta
branches:
  except:
    env:
      global:
        - PATH="$PATH:$TRAVIS_BUILD_DIR/target/debug"
        - RUST_BACKTRACE="1"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo
os:
  - osx
script:
  - cargo build --verbose
  - cargo run
