[package]
name = "top"
version = "0.1.0"
authors = ["Jeremy PEPIN <jpepin@student.42.fr>"]

[dependencies.libc]
version       = "0.2"

[[bin]]
name = "top"
test = false

[lib]
test = false
doctest = false
