[package]
name = "baum-rs"
version = "0.1.0"

[[bin]]
name = "baum-rs"
test = false

[lib]
test = false
doctest = false

[dependencies.libc]
version = "0.2"

[dependencies.clippy]
version = "*"
optional = true
